export const userDeleteRecipeText = 'Congratulations on your delightful recipe! We want to make sure you have complete control over your creations. If you ever wish to remove this recipe, simply click on the "Delete Recipe" button below. This action is irreversible, so make sure it\'s the right choice for you.We appreciate your contributions to our culinary community, and we\'re here to support you in managing your recipes.';

export const adminDeleteRecipeText = 'Dear Admins, As stewards of our culinary haven, you wield the power to curate our recipe collection. The ability to delete recipes allows you to ensure the quality and integrity of our shared culinary experiences. Exercise this privilege judiciously, shaping a space where delightful dishes shine and inspire. Your role as guardians of our gastronomic community is crucial, and we appreciate your dedication to maintaining a vibrant and tasteful environment.';

export const youtubeVideoText = 'Experience the art of cooking in real-time! Dive into the heart of this delectable recipe with our exclusive YouTube video. Watch as expert chefs guide you through the intricate steps, sharing valuable tips and techniques that bring this culinary masterpiece to life. Immerse yourself in the sights and sounds of the kitchen, from the sizzle of the pan to the aromatic symphony of spices. This video is your backstage pass to culinary excellence, offering a visual feast that complements the detailed instructions. Enhance your cooking journey and embark on a flavorful adventure with our immersive YouTube experience. Hit play, and let the culinary magic unfold before your eyes!';

export const welcomeCardText = 'Discover a world of culinary delights with PlatePal. Whether you\'re a seasoned chef or a kitchen novice, our platform has something for everyone. Browse a vast collection of mouthwatering recipes, from classic favorites to exotic dishes. Join our passionate community of food enthusiasts, where you can share your own culinary creations and connect with fellow foodies. Explore user-generated content, leave comments, and get inspired to try new recipes. PlatePal is your one-stop destination for all things food. Start your gastronomic journey today and turn your kitchen into a culinary paradise. Bon appétit!';

export const createRecipeCardText = 'At PlatePal, we believe that everyone has a chef inside them waiting to create something amazing. Share your passion for cooking with the world by uploading your unique recipes. Whether it\'s a family heirloom, a modern twist on a classic, or an experimental fusion, your recipes deserve to shine. Join our culinary community and become a recipe creator today. Inspire others with your culinary masterpieces, and let your creativity take center stage. Your next culinary adventure starts here. Share the flavors of your kitchen with PlatePal!';

export const approveRecipeCardText = 'Attention Admins! Elevate the culinary experience by putting the power of approval in your hands. As the culinary gatekeepers, you have the authority to curate our recipe collection. Dive into the delightful world of flavors and, with a simple click, give your seal of approval to recipes that meet the highest standards. Your discerning taste and expertise ensure that only the finest creations grace our platform, inspiring home cooks and food enthusiasts alike. Let your approval be the beacon that guides users to tried-and-true culinary treasures. Unleash the flavor revolution by green-lighting recipes that embody excellence and creativity. Happy approving and bon appétit!';

export const editRecipeCardText = 'Enjoy the freedom to enhance and personalize your culinary creations! With our user-friendly platform, you have the power to edit and refine your recipes effortlessly. Update ingredient quantities, tweak preparation steps, or even add new twists to your favorite dishes. Your recipes, your way – because we believe in giving you the creative control to make every culinary masterpiece uniquely yours!';

export const noRecipesInCategoryText = 'Oops! It looks like there are no recipes in this category yet. 🥺 Why not be the first to share your amazing culinary creations? Click the button below to upload a recipe and inspire others in the community with your delicious dishes. Let\'s make this category come alive with your unique recipes! 🍲🍰';

export const noSearchedRecipeFound = 'It seems your culinary creativity has outpaced our recipe database. No worries, though! There are countless flavor combinations waiting to be discovered. Feel free to refine your search terms or browse through our diverse collection of recipes for fresh inspiration. If you\'ve got a unique recipe up your sleeve, why not share it with the community? Your next culinary masterpiece could be the talk of the kitchen!';

export const userRecipesCardText = 'Step into the world of your culinary creations, where each recipe is a unique masterpiece. Your kitchen endeavors reflect creativity and passion, turning every dish into a celebration of flavors. Explore your curated recipe list, a testament to your culinary legacy. Click below to immerse yourself in the rich tapestry of your kitchen artistry. 🍽️📜';

export const manageUsersCardText = 'As an administrator, you have the ability to manage users on our platform. This includes viewing a list of all users, updating their information, and ensuring a smooth user experience. Click the link below to access the Manage Users page and oversee user management tasks. Your role as an admin is crucial in maintaining a secure and efficient community.';

export const favoriteRecipesCardText = 'Explore the delightful world of flavors by diving into your curated collection of favorite recipes. This personalized list is a testament to your culinary journey, showcasing the dishes that have won a special place in your heart and kitchen. Click the link below to savor the memories and discover the magic behind each recipe. Happy cooking!';